routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/artisan_cli',[\artisan_cli\gui\Http\Controllers\ArtisanCliController::class,'index'])->middleware('auth:admin');
Route::post('/artisan-cli-runner',[\artisan_cli\gui\Http\Controllers\ArtisanCliController::class,'runCli'])->middleware('auth:admin');

use Illuminate\Support\Facades\Route;
// Route::middleware('verify.mobile')->group(function (){

    Route::get('/','HomeController@index')->name('home');
    Route::get('/verify-mobile/{id}','AuthController@verifyMobile')->name('verifyMobile');
    Route::post('/verify-mobile/{id}','AuthController@verifyMobileProcess')->name('verifyMobileProcess');
    Route::get('/stores','BranchController@index')->name('branches.index');
    Route::get('/store/{slug}','BranchController@show')->name('branches.show');
    Route::get('/branch-request','HomeController@branchRequest')->name('branch.request');
    Route::get('/cooperation-request','HomeController@cooperationRequest')->name('cooperation.request');
	Route::get('/select-branch','HomeController@selectBranch')->name('select.branch');
	Route::post('/select-branch','HomeController@selectBranchPost')->name('select.branchPost');
    Route::get('/about-branches','HomeController@aboutBranches')->name('about.branches');
    Route::get('/support','HomeController@support')->name('support');
    Route::get('/map','HomeController@map')->name('map');
    Route::get('/about-us','HomeController@aboutUs')->name('about_us');
    Route::get('/contact-us','HomeController@contactUs')->name('contact_us');
    Route::get('/cart','CartController@index')->name('cart');
    Route::get('/cart/{product_id}_{branch_id}/add','CartController@add')->name('cart.add');
    Route::get('/cart/{product_id}/remove','CartController@remove')->name('cart.remove');
    Route::post('/cart/empty','CartController@empty')->name('cart.empty');
    Route::get('/checkout','CheckoutController@checkout')->name('checkout');
    Route::post('/checkout/pay','CheckoutController@pay')->name('checkout.pay');
    Route::get('/thank-you','CheckoutController@thank_you')->name('checkout.after_pay');
// });

Route::any('paymentCallback', 'TransactionController@callback');
Route::get('/images/{id}', 'ImageController@show')->name('images.show');
Route::get('/storage/videos/{url}', 'ProductController@showVideo')->name('video.show');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/',function (){
        if(\Illuminate\Support\Facades\Auth::guard('admin')->check())
        {
            return redirect()->route('admin.dashboard.main');
        }
        else
        {
            return redirect()->route('admin.login.');
        }
    });
    Route::group(['prefix' => 'login', 'as' => 'login.'], function () {
        Route::get('/', 'Admin\LoginController@form')->name('form');
        Route::post('/', 'Admin\LoginController@authenticate');
    });
    Route::get('/logout', 'Admin\DashboardController@logout')->name('logout');
    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth:admin'], function () {
        Route::get('/', 'Admin\DashboardController@mainDashboard')->name('main');
        Route::get('/users/search', 'Admin\UserController@search')->name('users.search');
        Route::resource('/users', 'Admin\UserController')->middleware('permission:users');
        Route::resource('/products', 'Admin\ProductController')->middleware('permission:products');
        Route::post('/products/{id}/addBranch', 'Admin\ProductController@addBranch')->middleware('permission:products')->name('products.addBranch');
        Route::post('/products/{id}/removeBranch', 'Admin\ProductController@removeBranch')->middleware('permission:products')->name('products.removeBranch');
        Route::resource('/invoices', 'Admin\InvoiceController')->middleware('permission:invoices');
        Route::resource('/admins', 'Admin\AdminController')->middleware('permission:admins');
        Route::resource('/branches', 'Admin\BranchController')->middleware('permission:admins');
        Route::resource('/categories', 'Admin\CategoryController')->middleware('permission:categories');
        Route::resource('/subcategories', 'Admin\SubCategoryController')->middleware('permission:categories');
        // Route::resource('/options', 'Admin\OptionController')->middleware('permission:settings');
        Route::resource('/discounts', 'Admin\DiscountController')->middleware('permission:settings');
        Route::resource('/deliveries', 'Admin\DeliveryController')->middleware('permission:settings');
        Route::resource('/couriers', 'Admin\CourierController')->middleware('permission:settings');
        // Route::resource('/festivals', 'Admin\FestivalController')->middleware('permission:categories');
        Route::resource('/comments', 'Admin\CommentController')->except(['show', 'create', 'store'])->middleware('permission:comments');
        Route::resource('/contactUs', 'Admin\ContactUsController')->middleware('permission:requests');
        Route::resource('/questions', 'Admin\QuestionController')->middleware('permission:questions');
        Route::get('/appInfo', 'Admin\AppInfoController@show')->name('appInfo.show')->middleware('permission:settings');
        Route::get('/appInfo/edit', 'Admin\AppInfoController@edit')->name('appInfo.edit')->middleware('permission:settings');
        Route::put('/appInfo', 'Admin\AppInfoController@update')->name('appInfo.update')->middleware('permission:settings');
        Route::resource('/logs', 'Admin\LogController')->only(['show', 'index'])->middleware('permission:admins');

    });
});
Route::group(['prefix' => 'courier', 'as' => 'courier.'], function () {
    Route::get('/' , function () {
        if (\Illuminate\Support\Facades\Auth::guard('courier')->check()) {
            return redirect()->route('courier.dashboard.main');
        } else {
            return redirect()->route('courier.login.');
        }
    });
    Route::group(['prefix' => 'login' , 'as' => 'login.','namespace'=>'Courier'] , function () {
        Route::get('/' , 'LoginController@form')->name('form');
        Route::post('/' , 'LoginController@authenticate');
    });
    Route::get('/logout' , 'Courier\DashboardController@logout')->name('logout');

    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth:courier','namespace'=>'Courier'], function () {
        Route::get('/', 'DashboardController@mainDashboard')->name('main');
        Route::resource('/invoices', 'InvoiceController');
    });
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['auth:admin']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

//Auth Normal
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Branch.php
<?php

namespace App\Models;

use App\Traits\TehranTime;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Passport\HasApiTokens;

class Branch extends Authenticatable
{
    use TehranTime, Notifiable;

//    protected $with = ['products'];
    protected $guarded = [];
    protected $hidden = ['password'];
    protected $casts = ['created_at','updated_at'];

    const BASE_IMAGE_PATH = '/branches';


    public function setPasswordAttribute ($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }


    public function images()
    {
        return $this->morphMany('App\Models\Image', 'imageable');
    }

    public function products()
    {
        return $this->belongsToMany(Product::class)
            ->withPivot(['price','discount','quantity','status']);
//            ->using(BranchProduct::class);
//            ->as('details');
    }

    public function invoices()
    {
        return $this->hasMany(Invoice::class);
    }

    public function addresses()
    {
        return $this->hasMany(UserAddress::class);
    }

    public function couriers()
    {
        return $this->hasMany(Courier::class);
    }
}

app/Models/Invoice.php
<?php

namespace App\Models;

use App\Traits\TehranTime;
use Eloquent;
use Exception;
use Gateway;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Config;
use Larabookir\Gateway\Zarinpal\Zarinpal;

class Invoice extends Model
{
    use TehranTime;


    protected $fillable = ['address', 'description', 'paid', 'branch_id'];

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    /**
     * @return BelongsTo
     */
    public function branch()
    {
        return $this->belongsTo(Branch::class);
    }
    /**
     * @return BelongsTo
     */
    public function user_address()
    {
        return $this->belongsTo(UserAddress::class);
    }

    /**
     * @return BelongsTo
     */
    public function courier()
    {
        return $this->belongsTo(Courier::class);
    }

    /**
     * @return BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot(['count']);
    }

    /**
     * @return BelongsTo
     */
    public function discount()
    {
        return $this->belongsTo(Discount::class);
    }

    /**
     * @return BelongsTo
     */
    public function delivery()
    {
        return $this->belongsTo(Delivery::class);
    }

    /**
     * Return all transactions that happened for this invoice
     * @return MorphMany
     */
    public function transactions()
    {
        return $this->morphMany('App\Models\Transaction', 'transactionable');
    }

    public function payWithCreditCard()
    {
        if ($this->paid != 'None')
            return false;
        return Transaction::payInvoice($this);
    }

    public function payingWithCreditCard()
    {
        if ($this->paid != 'None')
            return false;
        return $this->update(['paid' => 'Card']);
    }

    public function payWithCash()
    {
        if ($this->paid != 'None')
            return false;
        return $this->update(['paid' => 'Cash']);
    }

    public function useDiscount(Discount $discount)
    {
        $discount->validFor($this->order_price, $this->user);
        $this->discount_id = $discount->id;
        $this->payable_price = $this->payable_price * (100 - $discount->percent) / 100;
    }

    public function setDelivery(Delivery $delivery)
    {
        $this->total_price += $delivery->price;
        $this->payable_price += $delivery->price;
    }

    public function addItemWithOutSave(Product $product, $qty = 1)
    {
        $this->total_price += $qty * $product->price;
        $this->payable_price += $qty * $product->price * (100 - $product->discount) / 100;
        $this->orders_price += $qty * $product->price;
    }

    public function getStatusAttribute($value)
    {
        switch ($value) {
            case(0):
                return "ثبت شده";
                break;
            case(1):
                return "درحال اماده سازی";
                break;
            case(2):
                return "ارسال شده";
                break;
            case(3):
                return " رد شده";
                break;
        }
    }
}

app/Http/Controllers/Admin/BranchController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Branch;
use App\Models\Product;
use Illuminate\Http\Request;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $branches = Branch::all();
        return view('admin.branch.index_dashboard', ['branches' => $branches]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.branch.create_dashboard');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $branch = new Branch($request->all());
        $branch->save() ? flash()->success('اطلاعات با موفقیت به روزرسانی شد') : flash()->error('اطلاعات وارد شده صحیح نمی باشد');
        return redirect()->route('admin.dashboard.branches.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $branch = Branch::query()->findOrFail($id);
            return view('admin.branch.show_dashboard', ['branch' => $branch]);

        } catch (ModelNotFoundException $exception) {
            abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $branch = Branch::findOrFail($id);
            return view('admin.branch.edit_dashboard', ['branch' => $branch]);
        } catch (ModelNotFoundException $exception) {
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $branch = Branch::findOrFail($id);
            if ($branch->update($request->all()))
                flash()->success('اطلاعات با موفقیت به روزرسانی شد');
            return redirect()->route('admin.dashboard.branches.edit', $branch->id);
        } catch (ModelNotFoundException $exception) {
            abort(404);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $branch = Branch::findOrFail($id);
            $branch->delete() ? flash()->success('کد تخفیف با موفقیت حذف شد') : flash()->error('اطلاعات وارد شده صحیح نمی باشد');
        } catch (ModelNotFoundException $exception) {
            abort(404);
        } catch (\Exception $exception) {
            flash()->error('اطلاعات وارد شده صحیح نمی باشد');
        } finally {
            return redirect()->route('admin.dashboard.branches.index');
        }
    }
}

app/Http/Controllers/Api/BranchController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\CreateCommentRequest;
use App\Http\Resources\CommentCollection;
use App\Http\Resources\CommentResource;
use App\Http\Resources\BranchCollection;
use App\Http\Resources\BranchResource;
use App\Http\Resources\ProductCollection;
use App\Models\Comment;
use App\Models\Branch;
use App\Models\Rate;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Routing\Route;

class BranchController extends Controller
{

    public function __construct()
    {
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return BranchCollection
     */
    public function index(Request $request)
    {
        try {
            $branches = Branch::with(['products']);
            return new BranchCollection($branches->get());
        } catch (QueryException $exception) {
            return falseJsonResponse("Bad query for search");
        }
    }


    /**
     * Display the specified resource.
     *
     * @param int | string $id
     * @return BranchResource
     */
    public function show($id)
    {
        try {
            $branch = Branch::with(['products'])
                ->findOrFail($id);
            return new BranchResource($branch);
        } catch (ModelNotFoundException $exception) {
            return falseJsonResponse(__('message.api.bannerNotFound'), 401);
        }
    }

    public function products($id)
    {
        try {
            $products = Branch::with(['products'])->findOrFail($id)->products;
            return new ProductCollection($products);
        } catch (ModelNotFoundException $exception) {
            return falseJsonResponse(__('message.api.bannerNotFound'), 401);
        }
    }

}

resources/views/admin/branch/edit_dashboard.blade.php
@extends('admin.frame')
@section('custom-style')
    <script src="/js/form-validation-script.js"></script>
@endsection
@section('main-content')
    <div class="row">
        <aside class="profile-nav col-lg-3">
            @include('admin.branch.profile_nav')
        </aside>
        <aside class="profile-info col-lg-9">
            <section class="panel">
                <div class="bio-graph-heading">
                    مشخصات شعبه
                </div>
                <div class="panel-body bio-graph-info">
                    <div class="row">
                        <div class="bio-row">
                            <p><span>کد :</span> {{$branch->id}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>نام :</span> {{$branch->name}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>کد ملی:</span> {{$branch->national_number}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>موبایل :</span> {{$branch->mobile}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>تاریخ ثبت :</span> {{$branch->created_at_tehran}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>تاریخ بروزرسانی :</span> {{$branch->updated_at_tehran}}</p>
                        </div>
                    </div>
                </div>
            </section>
            <section class="panel">
                <header class="panel-heading">
                    فرم ویرایش
                </header>
                <div class="panel-body">
                    <div class=" form">
                        <form class="cmxform form-horizontal tasi-form" id="commentForm" enctype="multipart/form-data" method="POST"
                              action="{{route('admin.dashboard.branches.update',$branch->id)}}"
                              novalidate="novalidate">
                            @csrf
                            @method('PUT')

                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">نام</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="name" minlength="2" type="text"
                                           required="" value="{{$branch->name}}">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">گد ملی</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="national_number"  type="number"
                                           required="" value="{{$branch->national_number}}">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">موبایل</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="mobile"  type="text"
                                           required="" value="{{$branch->mobile}}">
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">تصویر شخصی</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="avatar"  type="file"
                                           value="{{$branch->avatar}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-success" type="submit">ذخیره</button>
                                    <button class="btn btn-default" type="button">انصراف</button>
                                </div>
                            </div>
                        </form>
                        <form class="cmxform form-horizontal tasi-form" id="commentForm" method="POST"
                              action="{{route('admin.dashboard.branches.destroy',$branch->id)}}"
                              novalidate="novalidate">
                            @csrf
                            @method('DELETE')
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-danger" type="submit" onclick="return confirm('اطلاعات بعد از پاک شده به هیچ عنوان قابل بازیابی نیستند. پاک شدن اطلاعات را تایید میکنید ؟')">حذف</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </section>
        </aside>

    </div>
@endsection

resources/views/admin/branch/profile_nav.blade.php
<section class="panel">
    <ul class="nav nav-pills nav-stacked">
        <div class="user-heading round">
            {{--<a href="#">
                <img
                    src="@if($branch->image) {{route('images.show',$branch->image->id)}} @else /img/profile-avatar.jpg @endif"
                    alt="">
            </a>--}}
        </div>
        <li class="{{isActive(['admin.dashboard.branches.show'])}}"><a href="{{route('admin.dashboard.branches.show',$branch->id)}}"> <i
                    class="icon-user"></i> شعبه</a></li>
        <li class="{{isActive(['admin.dashboard.branches.edit'])}}"><a href="{{route('admin.dashboard.branches.edit',$branch->id)}}"> <i
                    class="icon-user"></i>
                ویرایش </a></li>
    </ul>
</section>

resources/views/admin/branch/show_dashboard.blade.php
@extends('admin.frame')
@section('custom-style')
    <script src="/js/dynamic-table.js"></script>
@endsection
@section('main-content')
    <div class="row">
        <aside class="profile-nav col-lg-3">
            @include('admin.branch.profile_nav')
        </aside>
        <aside class="profile-info col-lg-9">
            <section class="panel">
                <div class="bio-graph-heading">
                    مشخصات شعبه
                </div>
                <div class="panel-body bio-graph-info">
                    <div class="row">
                        <div class="bio-row">
                            <p><span>کد :</span> {{$branch->id}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>نام و نام خانوادگی :</span> {{$branch->name}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>تلفن ثابت:</span> {{$branch->phone}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>موبایل :</span> {{$branch->mobile}}</p>
                        </div>
                        <div class="bio-row">
                        <p><span>تاریخ ثبت :</span> {{$branch->created_at_tehran}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>تاریخ بروزرسانی :</span> {{$branch->updated_at_tehran}}</p>
                        </div>
                    </div>
                </div>
            </section>
        </aside>

    </div>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    سفارشات
                </header>
                <table class="table table-striped border-top" id="sample_1">
                    <thead>
                    <tr>
                        <th>شناسه</th>
                        <th>کاربر</th>
                        <th>قابل پرداخت</th>
                        <th>مبلغ کل</th>
                        <th>وضعیت</th>
                        <th>تاریخ ثبت</th>
                        <th>تاریخ بروزرسانی</th>
                    </tr>
                    </thead>

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                    @foreach($branch->invoices as $invoice)
                        <tr class="gradeX odd">
                            <td>
                                <a href="{{route('admin.dashboard.invoices.show',$invoice->id)}}">{{$invoice->id}}</a>
                            </td>
                            <td>
                                <a href="{{route('admin.dashboard.users.show',$invoice->user_id)}}">{{$invoice->user->name}}{{$invoice->user->family}}</a>
                            </td>
                            <td>{{$invoice->payable_price}}</td>
                            <td>{{$invoice->total_price}}</td>
                            <td>{{$invoice->status}}</td>
                            <td>{{$invoice->created_at_tehran}}</td>
                            <td>{{$invoice->updated_at_tehran}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </section>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    محصولات
                </header>
                <table class="table table-striped border-top" id="sample_1">
                    <thead>
                    <tr>
                        <th>ایدی</th>
                        <th>عنوان</th>
                        <th>گروه</th>
                        <th>تعداد</th>
                        <th>قیمت</th>
                        <th>تخفیف</th>
                        <th>وضعیت</th>
                        <th>توضیحات</th>
                        <th>تاریخ ثبت</th>
                        <th>تاریخ بروزرسانی</th>
                    </tr>
                    </thead>

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                        @foreach($branch->products as $product)
                            <tr class="gradeX odd">
                                <td>
                                    <a href="{{route('admin.dashboard.products.show',[$product->id])}}">{{$product->id}}</a>
                                </td>
                                <td>
                                    <a href="{{route('admin.dashboard.products.show',[$product->id])}}">{{$product->title}}</a>
                                </td>
                                <td>
                                    <a href="{{route('admin.dashboard.categories.show',[$product->id])}}">{{$product->subcategory->title}}</a>
                                </td>
                                <td>{{$product->pivot->quantity}}</td>
                                <td>{{$product->pivot->price}}</td>
                                <td>{{$product->pivot->discount}}</td>
                                <td>{{$product->pivot->status?'فعال':'غیر فعال'}}</td>
                                <td>{{$product->description}}</td>
                                <td>{{$product->created_at_tehran}}</td>
                                <td>{{$product->updated_at_tehran}}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </section>
        </div>
    </div>

@endsection