routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/artisan_cli',[\artisan_cli\gui\Http\Controllers\ArtisanCliController::class,'index'])->middleware('auth:admin');
Route::post('/artisan-cli-runner',[\artisan_cli\gui\Http\Controllers\ArtisanCliController::class,'runCli'])->middleware('auth:admin');

use Illuminate\Support\Facades\Route;
// Route::middleware('verify.mobile')->group(function (){

    Route::get('/','HomeController@index')->name('home');
    Route::get('/verify-mobile/{id}','AuthController@verifyMobile')->name('verifyMobile');
    Route::post('/verify-mobile/{id}','AuthController@verifyMobileProcess')->name('verifyMobileProcess');
    Route::get('/stores','BranchController@index')->name('branches.index');
    Route::get('/store/{slug}','BranchController@show')->name('branches.show');
    Route::get('/branch-request','HomeController@branchRequest')->name('branch.request');
    Route::get('/cooperation-request','HomeController@cooperationRequest')->name('cooperation.request');
	Route::get('/select-branch','HomeController@selectBranch')->name('select.branch');
	Route::post('/select-branch','HomeController@selectBranchPost')->name('select.branchPost');
    Route::get('/about-branches','HomeController@aboutBranches')->name('about.branches');
    Route::get('/support','HomeController@support')->name('support');
    Route::get('/map','HomeController@map')->name('map');
    Route::get('/about-us','HomeController@aboutUs')->name('about_us');
    Route::get('/contact-us','HomeController@contactUs')->name('contact_us');
    Route::get('/cart','CartController@index')->name('cart');
    Route::get('/cart/{product_id}_{branch_id}/add','CartController@add')->name('cart.add');
    Route::get('/cart/{product_id}/remove','CartController@remove')->name('cart.remove');
    Route::post('/cart/empty','CartController@empty')->name('cart.empty');
    Route::get('/checkout','CheckoutController@checkout')->name('checkout');
    Route::post('/checkout/pay','CheckoutController@pay')->name('checkout.pay');
    Route::get('/thank-you','CheckoutController@thank_you')->name('checkout.after_pay');
// });

Route::any('paymentCallback', 'TransactionController@callback');
Route::get('/images/{id}', 'ImageController@show')->name('images.show');
Route::get('/storage/videos/{url}', 'ProductController@showVideo')->name('video.show');
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/',function (){
        if(\Illuminate\Support\Facades\Auth::guard('admin')->check())
        {
            return redirect()->route('admin.dashboard.main');
        }
        else
        {
            return redirect()->route('admin.login.');
        }
    });
    Route::group(['prefix' => 'login', 'as' => 'login.'], function () {
        Route::get('/', 'Admin\LoginController@form')->name('form');
        Route::post('/', 'Admin\LoginController@authenticate');
    });
    Route::get('/logout', 'Admin\DashboardController@logout')->name('logout');
    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth:admin'], function () {
        Route::get('/', 'Admin\DashboardController@mainDashboard')->name('main');
        Route::get('/users/search', 'Admin\UserController@search')->name('users.search');
        Route::resource('/users', 'Admin\UserController')->middleware('permission:users');
        Route::resource('/products', 'Admin\ProductController')->middleware('permission:products');
        Route::post('/products/{id}/addBranch', 'Admin\ProductController@addBranch')->middleware('permission:products')->name('products.addBranch');
        Route::post('/products/{id}/removeBranch', 'Admin\ProductController@removeBranch')->middleware('permission:products')->name('products.removeBranch');
        Route::resource('/invoices', 'Admin\InvoiceController')->middleware('permission:invoices');
        Route::resource('/admins', 'Admin\AdminController')->middleware('permission:admins');
        Route::resource('/branches', 'Admin\BranchController')->middleware('permission:admins');
        Route::resource('/categories', 'Admin\CategoryController')->middleware('permission:categories');
        Route::resource('/subcategories', 'Admin\SubCategoryController')->middleware('permission:categories');
        // Route::resource('/options', 'Admin\OptionController')->middleware('permission:settings');
        Route::resource('/discounts', 'Admin\DiscountController')->middleware('permission:settings');
        Route::resource('/deliveries', 'Admin\DeliveryController')->middleware('permission:settings');
        Route::resource('/couriers', 'Admin\CourierController')->middleware('permission:settings');
        // Route::resource('/festivals', 'Admin\FestivalController')->middleware('permission:categories');
        Route::resource('/comments', 'Admin\CommentController')->except(['show', 'create', 'store'])->middleware('permission:comments');
        Route::resource('/contactUs', 'Admin\ContactUsController')->middleware('permission:requests');
        Route::resource('/questions', 'Admin\QuestionController')->middleware('permission:questions');
        Route::get('/appInfo', 'Admin\AppInfoController@show')->name('appInfo.show')->middleware('permission:settings');
        Route::get('/appInfo/edit', 'Admin\AppInfoController@edit')->name('appInfo.edit')->middleware('permission:settings');
        Route::put('/appInfo', 'Admin\AppInfoController@update')->name('appInfo.update')->middleware('permission:settings');
        Route::resource('/logs', 'Admin\LogController')->only(['show', 'index'])->middleware('permission:admins');

    });
});
Route::group(['prefix' => 'courier', 'as' => 'courier.'], function () {
    Route::get('/' , function () {
        if (\Illuminate\Support\Facades\Auth::guard('courier')->check()) {
            return redirect()->route('courier.dashboard.main');
        } else {
            return redirect()->route('courier.login.');
        }
    });
    Route::group(['prefix' => 'login' , 'as' => 'login.','namespace'=>'Courier'] , function () {
        Route::get('/' , 'LoginController@form')->name('form');
        Route::post('/' , 'LoginController@authenticate');
    });
    Route::get('/logout' , 'Courier\DashboardController@logout')->name('logout');

    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth:courier','namespace'=>'Courier'], function () {
        Route::get('/', 'DashboardController@mainDashboard')->name('main');
        Route::resource('/invoices', 'InvoiceController');
    });
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['auth:admin']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

//Auth Normal
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Invoice.php
<?php

namespace App\Models;

use App\Traits\TehranTime;
use Eloquent;
use Exception;
use Gateway;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Config;
use Larabookir\Gateway\Zarinpal\Zarinpal;

class Invoice extends Model
{
    use TehranTime;


    protected $fillable = ['address', 'description', 'paid', 'branch_id'];

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    /**
     * @return BelongsTo
     */
    public function branch()
    {
        return $this->belongsTo(Branch::class);
    }
    /**
     * @return BelongsTo
     */
    public function user_address()
    {
        return $this->belongsTo(UserAddress::class);
    }

    /**
     * @return BelongsTo
     */
    public function courier()
    {
        return $this->belongsTo(Courier::class);
    }

    /**
     * @return BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot(['count']);
    }

    /**
     * @return BelongsTo
     */
    public function discount()
    {
        return $this->belongsTo(Discount::class);
    }

    /**
     * @return BelongsTo
     */
    public function delivery()
    {
        return $this->belongsTo(Delivery::class);
    }

    /**
     * Return all transactions that happened for this invoice
     * @return MorphMany
     */
    public function transactions()
    {
        return $this->morphMany('App\Models\Transaction', 'transactionable');
    }

    public function payWithCreditCard()
    {
        if ($this->paid != 'None')
            return false;
        return Transaction::payInvoice($this);
    }

    public function payingWithCreditCard()
    {
        if ($this->paid != 'None')
            return false;
        return $this->update(['paid' => 'Card']);
    }

    public function payWithCash()
    {
        if ($this->paid != 'None')
            return false;
        return $this->update(['paid' => 'Cash']);
    }

    public function useDiscount(Discount $discount)
    {
        $discount->validFor($this->order_price, $this->user);
        $this->discount_id = $discount->id;
        $this->payable_price = $this->payable_price * (100 - $discount->percent) / 100;
    }

    public function setDelivery(Delivery $delivery)
    {
        $this->total_price += $delivery->price;
        $this->payable_price += $delivery->price;
    }

    public function addItemWithOutSave(Product $product, $qty = 1)
    {
        $this->total_price += $qty * $product->price;
        $this->payable_price += $qty * $product->price * (100 - $product->discount) / 100;
        $this->orders_price += $qty * $product->price;
    }

    public function getStatusAttribute($value)
    {
        switch ($value) {
            case(0):
                return "ثبت شده";
                break;
            case(1):
                return "درحال اماده سازی";
                break;
            case(2):
                return "ارسال شده";
                break;
            case(3):
                return " رد شده";
                break;
        }
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index_dashboard', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.user.create_dashboard');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $info = $request->except('_token');
        try {
            $user = new User($info);
            $user->save() ? flash()->success('کاربر با موفقیت ثبت شد') : flash()->error('اطلاعات وارد شده صحیح نمی باشد');
        } catch (Exception $exception) {
            flash()->error('اطلاعات وارد شده صحیح نمی باشد');
        } finally {
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        try {
            $user = User::with(['invoices.delivery'])->findOrFail($id);
            return view('admin.user.show_dashboard', ['user' => $user]);
        } catch (ModelNotFoundException $exception) {
            return abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        try {
            $user = User::findOrFail($id);
            return view('admin.user.edit_dashboard', ['user' => $user]);
        } catch (ModelNotFoundException $exception) {
            return abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        try {
            $user = User::findOrFail($id);
            $user->update($request->except('_token')) ? flash()->success('اطلاعات با موفقیت به روزرسانی شد') : flash()->error('اطلاعات وارد شده صحیح نمی باشد');
            return view('admin.user.edit_dashboard', ['user' => $user]);
        } catch (ModelNotFoundException $exception) {
            return abort(404);
        } catch (Exception $exception) {
            flash()->error('اطلاعات وارد شده صحیح نمی باشد');
            return back();
        }
    }


    /**
     * Show the form for searching the specified resource.
     * @param Request $request
     * @return Factory|View
     */
    public function search(Request $request)
    {
        $users = User::orderByDesc('created_at');
        !$request->input('id') ?: $users->where('id', $request->input('id'));
        !$request->input('name') ?: $users->where('name', 'like', "%{$request->input('name')}%");
        !$request->input('family') ?: $users->where('family', 'like', "%{$request->input('family')}%");
        !$request->input('mobile') ?: $users->where('mobile', $request->input('mobile'));
        return view('admin.user.search_dashboard', ['users' => $users->get()]);
    }


}

resources/views/admin/user/create_dashboard.blade.php
@extends('admin.frame')
@section('custom-style')
    <script src="/js/form-validation-script.js"></script>
@endsection
@section('main-content')
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    فرم ثبت کاربر جدید
                </header>
                <div class="panel-body">
                    <div class=" form">
                        <form class="cmxform form-horizontal tasi-form" id="commentForm" method="POST"
                              action="{{route('admin.dashboard.users.store')}}" novalidate="novalidate">
                            @csrf
                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">نام (ضروری)</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="name" minlength="2" type="text"
                                           required="">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">نام خانوادگی (ضروری)</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="family" minlength="2" type="text"
                                           required="">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">موبایل (ضروری)</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="mobile" minlength="2" type="number"
                                           required="">
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">ایمیل (اختیاری)</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="email" minlength="4" type="email">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-danger" type="submit">ذخیره</button>
                                    <button class="btn btn-default" type="button">انصراف</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/admin/user/edit_dashboard.blade.php
@extends('admin.frame')
@section('custom-style')
    <script src="/js/form-validation-script.js"></script>
@endsection
@section('main-content')
    <div class="row">
        @include('admin.user.profile_nav')
        <aside class="profile-info col-lg-9">
            <section class="panel">
                <div class="bio-graph-heading">
                    مشخصات کاربر
                </div>
                <div class="panel-body bio-graph-info">
                    <div class="row">
                        <div class="bio-row">
                            <p><span>ایدی :</span> {{$user->id}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>نام و نام خانوادگی :</span> {{$user->name}} {{$user->family}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>شماره موبایل :</span> {{$user->mobile}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>ایمیل :</span> {{$user->email}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>تاریخ عضویت :</span> {{$user->created_at_tehran}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>تاریخ بروزرسانی :</span> {{$user->updated_at_tehran}}</p>
                        </div>

                    </div>
                </div>
            </section>
        </aside>

    </div>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    فرم ویرایش کاربر
                </header>
                <div class="panel-body">
                    <div class=" form">
                        <form class="cmxform form-horizontal tasi-form" id="commentForm" method="POST"
                              action="{{route('admin.dashboard.users.update',[ $user->id])}}"
                              novalidate="novalidate">
                            @csrf
                            @method('PUT')

                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">نام (ضروری)</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="name" minlength="2" type="text"
                                           required="" value="{{$user->name}}">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">نام خانوادگی (ضروری)</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="family" minlength="2" type="text"
                                           required="" value="{{$user->family}}">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">موبایل (ضروری)</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="mobile" minlength="2" type="number"
                                           required="" value="{{$user->mobile}}">
                                </div>
                            </div>
                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">ایمیل (اختیاری)</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="email" minlength="4" type="email"
                                           value="{{$user->email}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-danger" type="submit">ذخیره</button>
                                    <button class="btn btn-default" type="button">انصراف</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/admin/user/index_dashboard.blade.php
@extends('admin.frame')
@section('custom-style')
    <script src="/js/dynamic-table.js"></script>
@endsection
@section('main-content')
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    کاربران
                </header>
                <table class="table table-striped border-top" id="sample_1">
                    <thead>
                    <tr>
                        <th style="width:8px;"><input type="checkbox" class="group-checkable"
                                                      data-set="#sample_1 .checkboxes" title="جست و جو"/></th>
                        <th>ایدی</th>
                        <th class="hidden-phone">نام و نام خانوادگی</th>
                        <th class="hidden-phone">موبایل</th>
                        <th class="hidden-phone">وضعیت</th>
                        <th class="hidden-phone">تاریخ عضویت</th>
                        <th class="hidden-phone">تاریخ بروزرسانی</th>
                    </tr>
                    </thead>

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                    @isset($users)
                        @foreach($users as $user)
                            <tr class="gradeX odd">
                                <td class="  sorting_1"><input type="checkbox" class="checkboxes" value="1"></td>
                                <td class=" "><a
                                            href="{{route('admin.dashboard.users.show',[$user->id])}}">{{$user->id}}</a>
                                </td>
                                <td class=" "><a
                                            href="{{route('admin.dashboard.users.show',[ $user->id])}}">{{$user->name}} {{$user->family}}</a>
                                </td>
                                <td class="center hidden-phone ">{{$user->mobile}}</td>
                                <td class="center hidden-phone ">{{$user->statusLabel}}</td>
                                <td class="center hidden-phone ">{{$user->created_at_tehran}}</td>
                                <td class="center hidden-phone ">{{$user->updated_at_tehran}}</td>
                            </tr>
                        @endforeach
                    @endisset
                    </tbody>
                </table>
            </section>
        </div>
    </div>
@endsection

resources/views/admin/user/profile_nav.blade.php
<aside class="profile-nav col-lg-3">
    <section class="panel">
        <div class="user-heading round">
            <h1>{{$user->name}} {{$user->family}}</h1>
            <p>{{$user->mobile}}</p>
        </div>

        <ul class="nav nav-pills nav-stacked">
            <li class="{{isActive(['admin.dashboard.users.show'])}}"><a href="{{route('admin.dashboard.users.show',[ $user->id])}}"> <i
                        class="icon-user"></i> پروفایل</a></li>
            <li class="{{isActive(['admin.dashboard.users.edit'])}}"><a href="{{route('admin.dashboard.users.edit',[$user->id])}}"> <i class="icon-user"></i>
                    ویرایش پروفایل</a></li>
        </ul>
    </section>
</aside>

resources/views/admin/user/show_dashboard.blade.php
@extends('admin.frame')
@section('custom-style')
    <script src="/js/dynamic-table.js"></script>
@endsection
@section('main-content')
    <div class="row">
        @include('admin.user.profile_nav')
        <aside class="profile-info col-lg-9">
            <section class="panel">
                <div class="bio-graph-heading">
                    مشخصات کاربر
                </div>
                <div class="panel-body bio-graph-info">
                    <div class="row">
                        <div class="bio-row">
                            <p><span>ایدی :</span> {{$user->id}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>نام و نام خانوادگی :</span> {{$user->name}} {{$user->family}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>شماره موبایل :</span> {{$user->mobile}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>ایمیل :</span> {{$user->email}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>تاریخ عضویت :</span> {{$user->created_at_tehran}}</p>
                        </div>
                        <div class="bio-row">
                            <p><span>تاریخ بروزرسانی :</span> {{$user->updated_at_tehran}}</p>
                        </div>

                    </div>
                </div>
            </section>
        </aside>

    </div>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    خرید ها
                    </header>

                <table class="table table-striped border-top" id="sample_1">
                    <thead>
                    <tr>
                        <th>ایدی</th>
                        <th class="hidden-phone">مبلغ کل</th>
                        <th class="hidden-phone">مبلغ قابل پرداخت</th>
                        <th class="hidden-phone">وضعیت</th>
                        <th class="hidden-phone">ادرس</th>
                        <th class="hidden-phone">تاریخ ثبت</th>
                        <th class="hidden-phone">تاریخ بروزرسانی</th>
                    </tr>
                    </thead>

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                    @isset($user->invoices)
                        @foreach($user->invoices as $invoice)
                            <tr class="gradeX odd">
                                <td class=" "><a href="{{route('admin.dashboard.invoices.show',[$invoice->id])}}">{{$invoice->id}}</a></td>
                                <td class="hidden-phone ">{{$invoice->total_price}}</td>
                                <td class="hidden-phone ">{{$invoice->payable_price}}</td>
                                <td class="center hidden-phone ">{{$invoice->status}}</td>
                                <td class="center hidden-phone ">{{$invoice->address}}</td>
                                <td class="center hidden-phone ">{{$invoice->created_at_tehran}}</td>
                                <td class="center hidden-phone ">{{$invoice->updated_at_tehran}}</td>
                            </tr>
                        @endforeach
                    @endisset
                    </tbody>
                </table>
            </section>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    تراکنش ها
                </header>

                <table class="table table-striped border-top" id="sample_2">
                    <thead>
                    <tr>
                        <th>ایدی</th>
                        <th>ایدی فاکتور</th>
                        <th class="hidden-phone">درگاه</th>
                        <th class="hidden-phone">قیمت</th>
                        <th class="hidden-phone">ref id</th>
                        <th class="hidden-phone">وضعیت</th>
                        <th class="hidden-phone">ip</th>
                        <th class="hidden-phone">تاریخ شروع</th>
                        <th class="hidden-phone">تاریخ پایان</th>
                    </tr>
                    </thead>

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                    @foreach($user->getTransactions() as $transaction)
                        <tr class="gradeX odd">
                            <td class=" ">{{$transaction->id}}</td>
                            <td class=" "><a href="{{route('admin.dashboard.invoices.show',[$transaction->transactionable_id])}}">{{$transaction->transactionable_id}}</a></td>
                            <td class=" ">{{$transaction->port}}</td>
                            <td class="center hidden-phone ">{{$transaction->price}}</td>
                            <td class="center hidden-phone ">{{$transaction->ref_id}}</td>
                            <td class="center hidden-phone ">{{$transaction->status}}</td>
                            <td class="center hidden-phone ">{{$transaction->ip}}</td>
                            <td class="center hidden-phone ">{{$transaction->created_at_tehran}}</td>
                            <td class="center hidden-phone ">{{$transaction->updated_at_tehran}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </section>
        </div>
    </div>

@endsection